appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: vGc5on466XqdhGcI0L1gRJ9d/5vTWcs9wkzR/s8PH3j9QhN/QW6PxM3NBOVkhpHOR2Ij/dN81c3pvVNslNuLaz4JpF/EGIKJwfRv0bMrcXPz+Y02a2Zb6dB0Ok1sBWuaGBRfk5C9OhrE24G5yn0Jon7cXfIPmtVzuKh/SydMuIEGoLJ/PCtNP/lKyPWB8nOmXsvk6OeTCjVBmvczbVSiZRIGu0UySzFV0UmjgBPVwLLKtiKfDr/bey9h5Pc2QLDVQcSwF9Whu61ukppBK/LgF6fI4zBqiDoQwuC4g+CkB5a4JksqITx/wxDCQSisKqESDNIakShOy0CMYwfKQ8MbtXYjBhGUF5ciAuCETBow1mWvGavGQmzrDHiLeSW9jdjyRDzjQVO+od0YAhvmD2qoGYd2rXCRRJQhC7VLu4lT+4woPBCGvNVH6oAmS+7+ONdr7qEeNfRXC584aS241OLGe/DldV6QT0W/ADp8li7Ob6HCY29cA0RpukSAWr4aosd/8UmvfhV1OfFBY8tnxxPl3DvrAPBWo3jWynr1Zk+2G7g5ucQjKmBxLJFEMfe5Qz7B4UOvC/IoYJ4hVaxpVlUrWjAx9gQB1rVNUmGvaHodiJ4KpKrgJUMKfGASVqh8vvyZ/msTyHjesUJRbabxA21WU3UiS1G12tJB0pZUMx3KWoM=}
