travis:
  secure:
    BINSTAR_TOKEN: QBSAd8NvI0+M3PyYufAzKvchbYlRX7kw5StGzLQtN4Sy7FLVmYqiIXtWCkcvcmRdNkPXLDI7OIvu0/VouUW2tM4CJoa1aMfEGRymR9+GSwrbwNkTbPAvTDma869ADzx+Dxg1czsw07w1P4Qw+6A10VzY4w8iFMFhD6TD75Sg/dfXUv7cSR/hZgX1tYu0gXHuFBRX2xB1+ydn3Hb0t8B/nfT1/OfA/1h1HEyytj2UrEbF+YknRUKYygI3c44C93JuLuSDmG52ahxVmKLzFjm2oChme5IgF3wX2hOSLrujVjMwHGEoMdP5yQmuJTpJfFW1+wL5+00kOuDYNyBZSySfDU2VgE6P7eVNvduoNFuPKg8ErftBXD/qe97A8i8c6OH1rjctPpGgOLZB1vmnL+9fwPYU+a8dwtBfzWpiDOOAGjzsTHaIm97OBavPrA8pNe3ABSALa3lc2lBHwf2Nn9pLGyuKn8mu/W/ExvTzGHXeE5KnIEotgKzmh3On3w/w1r9WAxxAZLG2YnnEfpO4GuUkVQMK/bhSb+uCsFFmZCQbl6KIzQxetSFwDayxOYcCSDXEcrKAbLRrWNCqKgzQ/Xfi0mnQ8VNw25YAAUc++rpshyXaa41BUhuS+qkuZZMvQgNfckyeTyB9XbhNKBXHIWQU/VFGsV28e3kH0lFxHD1HMmc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
