travis:
  secure:
    BINSTAR_TOKEN: BKJ1mFkOj8w8j6Gfnl7ouqUMtw5qy4usXgZJpJP/dZy31t7/2AUyYtagiHVCc6tnhGdw1CKrkCZdXu763ypzHzEha6ftaS/oi4ps4TivmjBAOqMUlHMDyVOHb0qW7dTss6lh3BUa5UZPDJLh1OriXIS3BK8WeFKCrGN7TV+aXzS1O0xzjl14dcL0oRqA8R7mTpysWWE1F9H1xep93DPCWVvxcRX3qrQ+4g9dasv91KMqoHelFmV1OA5QaAMf5FfZoHeHr074vlpK6BxN7XWv/wwNV8DJN9wowftCunS/BTHR54cSD9XszQ/uOC34v1LnpakzIeTLpcLkcYSuqbp+aD77lS0+nzApvyemkAf5JrOIXHR8b9KyQXSOX9TvHHlD33L0kXAL1eXATN0y8PQLRng4Vc4njivc78Bq0T+qgtP0gNXWzvHpQmyk/IjHE8rbHNxkhwum+qlBipk7ygvRFzx6CV0fyiS8hv4n/yY7XD6oMXRFxaj7HtRNC7wmWJvkawFsXsDcsbpXsid+CgXrES2aoVcLwr0q8JVnykuzbvBn/ktHjDmgORg1sRRp0hQkRXBje1gZdf7DRpTvSVTbgHZFuOMAwlHf8rJNUKqzLPCKcQwbgwDmiKOOUrcR1TZYzYMxDdNxF8cUFdaIuWlc+0t77RQmapV2rl9XuJDFqPU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
